# Generated by Django 4.2.16 on 2024-11-09 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Skool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='assets/')),
                ('designationEcole', models.CharField(max_length=255)),
                ('arreteMin', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('typesEcole', models.CharField(max_length=50)),
                ('promoteur', models.CharField(max_length=255)),
                ('biographie', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=150)),
                ('classe', models.CharField(max_length=50)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='appFindSkool.degree')),
            ],
        ),
        migrations.AddField(
            model_name='degree',
            name='skool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='appFindSkool.skool'),
        ),
    ]
